=begin
#PharmaTrace Supply Chain Information Network API

#The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.

OpenAPI spec version: 0.0.1
Contact: api@pharmatrace.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.2

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ContainerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContainerApi' do
  before do
    # run before each test
    @instance = OpenapiClient::ContainerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContainerApi' do
    it 'should create an instance of ContainerApi' do
      expect(@instance).to be_instance_of(OpenapiClient::ContainerApi)
    end
  end

  # unit tests for location_history_get
  # Location History
  # Returns the location history of a container or a individually labeled pharmaceutical
  # @param [Hash] opts the optional parameters
  # @option opts [String] :container_id container id of the tracked container.
  # @option opts [Integer] :offset Offset the list of returned results by this amount. Default is zero.
  # @option opts [Integer] :limit Number of items to retrieve. Default is 5, maximum is 100.
  # @return [Locations]
  describe 'location_history_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
