=begin
#PharmaTrace Supply Chain Information Network API

#The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.

OpenAPI spec version: 0.0.1
Contact: api@pharmatrace.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/activities'
require 'openapi_client/models/activity'
require 'openapi_client/models/container'
require 'openapi_client/models/containers'
require 'openapi_client/models/error'
require 'openapi_client/models/information_query'
require 'openapi_client/models/information_query_response'
require 'openapi_client/models/legal_tx_terms'
require 'openapi_client/models/location'
require 'openapi_client/models/locations'
require 'openapi_client/models/pharmaceutical'
require 'openapi_client/models/pharmaceutical_list'
require 'openapi_client/models/profile'
require 'openapi_client/models/repackage'
require 'openapi_client/models/stakeholder'
require 'openapi_client/models/system_information'
require 'openapi_client/models/system_informations'
require 'openapi_client/models/trade'
require 'openapi_client/models/transaction'
require 'openapi_client/models/transport'
require 'openapi_client/models/wallet'

# APIs
require 'openapi_client/api/activitys_api'
require 'openapi_client/api/container_api'
require 'openapi_client/api/containers_api'
require 'openapi_client/api/information_query_responses_api'
require 'openapi_client/api/information_querys_api'
require 'openapi_client/api/legal_tx_termss_api'
require 'openapi_client/api/locations_api'
require 'openapi_client/api/pharmaceuticals_api'
require 'openapi_client/api/profiles_api'
require 'openapi_client/api/repackages_api'
require 'openapi_client/api/stakeholders_api'
require 'openapi_client/api/system_informations_api'
require 'openapi_client/api/trades_api'
require 'openapi_client/api/transports_api'
require 'openapi_client/api/user_api'
require 'openapi_client/api/wallets_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
